# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: 97xiami/97xiami.github.io
  branch: main

media_folder: /static/media
public_folder: /media

i18n:
  structure: multiple_folders
  locales: [ch, en]

collections:
  - name: posts
    label: Posts
    folder: /content/posts
    i18n: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
